name: EventHub CI

# 1. On dit à GitHub Actions de se déclencher UNIQUEMENT quand tu pousses sur "uat"
on:
  push:
    branches: [ "uat" ]

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #historique complet pour les merges

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test

      - name: Auto-merge uat vers main
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git fetch origin main
          
          git checkout main
          
          git merge origin/uat -m "Auto-merge de UAT vers main après tests réussis"
          
          git push origin main